# PCA

In [ ]:
from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig

In [ ]:
#define matrix
A = array([[1,2],[3,4],[5,6]])
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
#Calculate the mean of each column
M = mean(A.T, axis=1)
print(M)
print(A.T)

[3. 4.]
[[1 3 5]
 [2 4 6]]


In [ ]:
#center columns by substracting column means
C = A-M
print(C)

[[-2. -2.]
 [ 0.  0.]
 [ 2.  2.]]


In [ ]:
#calculate covariance matrix of centerred matrix
V = cov(C.T)
print(V)

[[4. 4.]
 [4. 4.]]


In [ ]:
#eigender composition of covariance matrix
values, vectors = eig(V)
print(vectors)
print(values)

[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
[8. 0.]


In [ ]:
#project data
P = vectors.T.dot(C.T)
print(P.T)

[[-2.82842712  0.        ]
 [ 0.          0.        ]
 [ 2.82842712  0.        ]]
